# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('two_factor', '0005_auto_20160224_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='X509Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('cert_dn', models.CharField(help_text='Certificate matter to match on.', max_length=1024, unique=True)),
                ('user', models.ForeignKey(blank=True, default=None, help_text='Django User associated with certificate.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_x509device_related', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
